const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const {pathToFileURL}=require('node:url');const {chromium}=require('playwright');
async function withPage(run){const b=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});try{const p=await b.newPage({viewport:{width:820,height:1180}});p.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());await p.addInitScript(()=>localStorage.setItem('keiyaku_welcome_seen_v1','1'));await p.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await p.waitForFunction(()=>document.body.dataset.appReady==='true');await run(p);}finally{await b.close();}}
async function seed(p,extra=true){assert.equal(await p.evaluate(async()=>typeof AudioRecorder),'undefined');await p.evaluate(async extra=>{const pdf=await PDFLib.PDFDocument.create();pdf.addPage([595,842]);const fields=[Models.createField({id:'one',x:50,y:660,width:180,height:45}),Models.createField({id:'ra',type:'recipient_address',x:50,y:600,width:360,height:50})];if(extra)fields.push(Models.createField({id:'two',x:50,y:400,width:180,height:45,signOrder:2}),Models.createField({id:'fa',type:'address',linkedFieldId:'two',assignedRole:'family',x:50,y:330,width:360,height:50}));await TemplateStore.saveNew(Models.createTemplate({name:'入力改善テスト',signingMode:extra?'all':'single',pdfBase64:await pdf.saveAsBase64(),pages:[{widthPt:595,heightPt:842,fields}]}));},extra);await p.locator('#btn-nav-home').click();}
test('見本表示と文字サイズスライダーが枠の見本へ即時反映される',async()=>withPage(async p=>{
 await seed(p,false);await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('.field-box[data-field-id=ra]').click();
 assert.match(await p.locator('.field-box[data-field-id=ra]').innerText(),/印字見本/);
 const slider=p.getByLabel('文字サイズを調整');assert.equal(await slider.inputValue(),'14');
 await slider.evaluate(el=>{el.value='18';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await p.getByLabel('文字サイズ（pt・枠に合わせて縮小）',{exact:true}).inputValue(),'18');
 if(process.env.USABILITY_SCREENSHOTS) await p.screenshot({path:path.join(process.env.USABILITY_SCREENSHOTS,'editor.png'),fullPage:true});
 await p.getByLabel('印字見本を表示').uncheck();assert.equal(await p.locator('.field-box-print-preview').count(),0);
}));
test('代理人の不足理由を表示し、根拠・住所・署名が揃った後は確定できる',async()=>withPage(async p=>{
 await seed(p);await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);t.pages[0].fields.push(Models.createField({id:'fr',type:'relationship',linkedFieldId:'two',assignedRole:'family',required:true,x:50,y:290,width:180,height:30}));await TemplateStore.saveEdit(t);});await p.getByRole('button',{name:'これで署名する'}).click();await p.locator('#signing-recipient-name').fill('本人');await p.locator('#signing-recipient-address').fill('本人住所');await p.locator('#signing-recipient-building').fill('本人マンション101');await p.locator('#signing-primary-role').selectOption('family');await p.locator('#signing-family-capacity').selectOption('representative');await p.getByRole('button',{name:'次へ進む'}).click();await p.getByRole('button',{name:'続ける',exact:true}).click();assert.equal(await p.getByRole('button',{name:/録音/}).count(),0);await p.locator('.signing-field-highlight').click();
 assert.equal(await p.getByRole('heading',{name:'代理人ご自身のお名前を署名してください'}).isVisible(),true);
 await p.getByLabel('実際に記入するご家族のお名前',{exact:true}).fill('娘');assert.match(await p.locator('#signer-missing-reasons').innerText(),/代理権/);
 await p.getByLabel('ご本人との関係・立場（任意）',{exact:true}).fill('長女');
 await p.getByRole('checkbox',{name:/代理人として/}).check();await p.getByLabel('代理権の根拠').fill('本人からの委任状を確認');
 if(process.env.USABILITY_SCREENSHOTS) await p.screenshot({path:path.join(process.env.USABILITY_SCREENSHOTS,'representative.png'),fullPage:true});
 const box=await p.locator('#signature-canvas').boundingBox();await p.mouse.move(box.x+20,box.y+20);await p.mouse.down();await p.mouse.move(box.x+120,box.y+20,{steps:12});await p.mouse.up();
 assert.equal(await p.getByRole('button',{name:'1画戻す',exact:true}).isEnabled(),true);
 const tools=await p.locator('.signature-tools').boundingBox();const writing=await p.locator('#signature-canvas').boundingBox();assert.ok(tools.y+tools.height<=writing.y);
 await p.getByRole('button',{name:'1画戻す',exact:true}).click();assert.equal(await p.getByRole('button',{name:'この内容で確定する',exact:true}).isEnabled(),false);
 await p.mouse.move(box.x+20,box.y+20);await p.mouse.down();await p.mouse.move(box.x+120,box.y+20,{steps:12});await p.mouse.up();
 assert.equal(await p.getByRole('button',{name:'この内容で確定する',exact:true}).isEnabled(),true);await p.getByRole('button',{name:'この内容で確定する',exact:true}).click();
 assert.match(await p.locator('#signing-stage').innerText(),/先ほど代理署名/);
 assert.equal(await p.evaluate(async()=>SigningFlow.getSession().signers[0].relationship),'長女');
 await p.getByRole('button',{name:'先ほど代理署名したご家族が続けて署名'}).click();await p.locator('.signing-field-highlight').click();
 assert.equal(await p.getByLabel('ご本人との関係・立場（必須）',{exact:true}).inputValue(),'長女');
 assert.equal(await p.getByLabel('代理権の根拠').isVisible(),false);
}));
test('登録した事業所・担当者を選択し、交付記録を画面で読める',async()=>withPage(async p=>{
 await p.getByRole('button',{name:'事業所・担当者を登録'}).click();await p.getByLabel('登録する事業所名').fill('登録事業所');await p.getByLabel('担当者名（1行に1人）').fill('担当A\n担当B');await p.getByRole('button',{name:'登録を保存'}).click();await p.reload();await p.waitForFunction(()=>document.body.dataset.appReady==='true');
 assert.equal(await p.evaluate(async()=>OperatorSettings.load().providerName),'登録事業所');
 await seed(p,false);await p.getByRole('button',{name:'これで署名する'}).click();await p.locator('#signing-recipient-name').fill('本人');await p.locator('#signing-recipient-address').fill('住所');await p.getByRole('button',{name:'次へ進む'}).click();
 await p.getByRole('button',{name:'続ける',exact:true}).click();await p.locator('.signing-field-highlight').click();const canvas=await p.locator('#signature-canvas').boundingBox();await p.mouse.move(canvas.x+20,canvas.y+30);await p.mouse.down();await p.mouse.move(canvas.x+130,canvas.y+30,{steps:12});await p.mouse.up();await p.getByRole('button',{name:'この内容で確定する',exact:true}).click();assert.equal(await p.getByLabel('事業所名',{exact:true}).inputValue(),'登録事業所');await p.getByLabel('登録した担当者を選ぶ').selectOption('担当B');assert.equal(await p.locator('#review-staff-input').inputValue(),'担当B');assert.equal(await p.locator('#review-staff-input').isVisible(),false);if(process.env.USABILITY_SCREENSHOTS) await p.screenshot({path:path.join(process.env.USABILITY_SCREENSHOTS,'staff.png'),fullPage:true});
 await p.getByLabel('登録した担当者を選ぶ').selectOption('__manual__');await p.getByLabel('説明・確認した担当者名').fill('別担当');assert.equal(await p.locator('#review-staff-input').inputValue(),'別担当');
 await p.locator('#btn-nav-home').click();await p.locator('#btn-open-verification').click();
 const receipt={format:'keiyaku-delivery',schemaVersion:1,verificationId:'test',finalPdfHashSha256:'a'.repeat(64),recordedAt:'2026-10-02T00:00:00Z',operator:{providerName:'登録事業所',staffName:'担当A'},method:'paper',recipient:'本人',status:'delivered',detail:'対面で交付'};
 await p.locator('#verify-delivery-input').setInputFiles({name:'交付記録.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(receipt))});await p.getByRole('button',{name:'交付記録を読む'}).click();await p.locator('#delivery-record-result').getByText(/交付結果/).waitFor();assert.match(await p.locator('#delivery-record-result').innerText(),/控えを渡した/);assert.match(await p.locator('#delivery-record-result').innerText(),/担当A/);
}));
test('暗号化JSONで途中保存し、拡張子制限なしで新旧ファイルから再開できる',async()=>withPage(async p=>{
 await seed(p);await p.getByRole('button',{name:'これで署名する'}).click();await p.locator('#signing-recipient-name').fill('途中本人');await p.locator('#signing-recipient-address').fill('途中住所');await p.getByRole('button',{name:'次へ進む'}).click();
 await p.evaluate(async()=>{const c=document.createElement('canvas');c.width=100;c.height=40;c.getContext('2d').fillRect(5,5,80,20);SigningFlow.submitCurrentSigner({role:'recipient',typedName:'途中本人',signatureImageDataUrl:c.toDataURL()});});
 await p.getByRole('button',{name:'続ける',exact:true}).click();await p.locator('.signing-field-highlight').click();await p.getByLabel(/^(お名前|署名する方のお名前)$/,{exact:true}).fill('途中家族');await p.getByLabel('記入者住所（PDF印字用・必須）').fill('家族住所');await p.getByLabel('記入者の建物名・部屋番号（任意）').fill('家族マンション202');await p.getByRole('button',{name:'書面に戻る',exact:true}).click();
 await p.getByRole('button',{name:'途中保存（暗号化）',exact:true}).click();await p.getByLabel('途中保存用パスワード').fill('draft-password-123');await p.getByLabel('パスワードをもう一度').fill('draft-password-123');await p.getByRole('button',{name:'暗号化して保存'}).click();const download=p.waitForEvent('download');await p.getByRole('button',{name:'途中保存ファイルを端末へ保存'}).click();const saved=await download;assert.match(saved.suggestedFilename(),/^契約途中保存_\d+\.json$/);const bytes=await fs.readFile(await saved.path());assert.ok(!bytes.toString().includes('途中本人'));assert.equal(JSON.parse(bytes.toString()).format,'keiyaku-encrypted-draft');
 await p.reload();await p.waitForFunction(()=>document.body.dataset.appReady==='true');assert.equal(await p.evaluate(async()=>SigningFlow.getSession()),null);
 await p.getByRole('button',{name:'途中保存ファイルから再開'}).click();assert.equal(await p.locator('#draft-restore-file').getAttribute('accept'),null);await p.locator('#draft-restore-file').setInputFiles({name:'途中保存.json',mimeType:'application/json',buffer:bytes});await p.getByLabel('途中保存用パスワード').fill('draft-password-123');await p.getByRole('button',{name:'復元して再開'}).click();await p.getByRole('heading',{name:/端末をお渡し/}).waitFor();
 assert.equal(await p.evaluate(async()=>SigningFlow.getSession().recipientName),'途中本人');assert.equal(await p.evaluate(async()=>SigningFlow.getCurrentField().id),'two');assert.equal(await p.evaluate(async()=>SigningFlow.getSession().signers.length),1);
 await p.getByRole('button',{name:'続ける',exact:true}).click();await p.locator('.signing-field-highlight').click();assert.equal(await p.getByLabel(/^(お名前|署名する方のお名前)$/,{exact:true}).inputValue(),'途中家族');assert.equal(await p.getByLabel('記入者の建物名・部屋番号（任意）').inputValue(),'家族マンション202');
 await p.reload();await p.waitForFunction(()=>document.body.dataset.appReady==='true');await p.getByRole('button',{name:'途中保存ファイルから再開'}).click();
 await p.locator('#draft-restore-file').setInputFiles({name:'別の記録.json',mimeType:'application/json',buffer:Buffer.from('{"format":"keiyaku-delivery"}')});await p.getByLabel('途中保存用パスワード').fill('draft-password-123');await p.getByRole('button',{name:'復元して再開'}).click();await p.getByText('未対応の途中保存ファイルです。',{exact:true}).waitFor();assert.equal(await p.evaluate(async()=>SigningFlow.getSession()),null);
 await p.locator('#draft-restore-file').setInputFiles({name:'以前の途中保存.keiyaku',mimeType:'application/octet-stream',buffer:bytes});await p.getByRole('button',{name:'復元して再開'}).click();await p.getByRole('heading',{name:/端末をお渡し/}).waitFor();assert.equal(await p.evaluate(async()=>SigningFlow.getSession().recipientName),'途中本人');
}));

test('新しい日付欄は16ptで、バーと表示形式が枠内の見本に反映される',async()=>withPage(async p=>{
 await seed(p,false);await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);t.pages[0].fields.push(Models.createField({id:'dt',type:'date',linkedFieldId:'one',x:50,y:500,width:300,height:45}));await TemplateStore.saveEdit(t);});await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('.field-box[data-field-id=dt]').click();
 const slider=p.getByLabel('文字サイズを調整');assert.equal(await slider.inputValue(),'16');
 const preview=p.locator('.field-box[data-field-id=dt] .field-box-print-preview');assert.equal(await preview.innerText(),'2026/9/23');const before=await preview.evaluate(el=>parseFloat(el.style.fontSize));
 await slider.evaluate(el=>{el.value='20';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await p.getByLabel('文字サイズ（pt・枠に合わせて縮小）',{exact:true}).inputValue(),'20');assert.ok(await preview.evaluate(el=>parseFloat(el.style.fontSize))>before);
 await p.getByLabel('日付の表示形式').selectOption('reiwa');assert.equal(await preview.innerText(),'令和8年9月23日');await p.getByLabel('日付の表示形式').selectOption('gregorian_kanji');assert.equal(await preview.innerText(),'2026年9月23日');
 assert.equal(await p.evaluate(async()=>Models.createField({type:'date',fontSize:11}).fontSize),11);
}));
test('署名順は住所項目に影響されず、既存の欠番・並べ替え・追加・削除を全ページで扱う',async()=>withPage(async p=>{
 await p.evaluate(async()=>{const pdf=await PDFLib.PDFDocument.create();pdf.addPage([595,842]);pdf.addPage([595,842]);await TemplateStore.saveNew(Models.createTemplate({name:'署名順テスト',signingMode:'all',pdfBase64:await pdf.saveAsBase64(),pages:[{widthPt:595,heightPt:842,fields:[Models.createField({id:'a',type:'recipient_address',x:50,y:700,width:300,height:40}),Models.createField({id:'s1',x:50,y:600,width:200,height:45,signOrder:1})]},{widthPt:595,heightPt:842,fields:[Models.createField({id:'s2',x:50,y:600,width:200,height:45,signOrder:4}),Models.createField({id:'ad',type:'address',linkedFieldId:'s2',x:50,y:500,width:300,height:40})]}]}));});await p.locator('#btn-nav-home').click();await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();
 assert.deepEqual(await p.evaluate(async()=>FieldEditor.getSignatureFields().map(f=>[f.id,f.signOrder])),[['s1',1],['s2',2]]);
 await p.locator('.field-box[data-field-id=s1]').click();await p.getByLabel('署名する順番',{exact:true}).fill('2');assert.deepEqual(await p.evaluate(async()=>FieldEditor.getSignatureFields().map(f=>[f.id,f.signOrder])),[['s2',1],['s1',2]]);
 await p.locator('#btn-next-page').click();await p.locator('.field-box[data-field-id=ad]').waitFor();await p.getByRole('button',{name:/^手書き署名/}).click();await p.locator('#field-overlay').scrollIntoViewIfNeeded();const overlay=await p.locator('#field-overlay').boundingBox();await p.mouse.move(overlay.x+500,overlay.y+100);await p.mouse.down();await p.mouse.move(overlay.x+620,overlay.y+145,{steps:8});await p.mouse.up();assert.deepEqual(await p.evaluate(async()=>FieldEditor.getSignatureFields().map(f=>f.signOrder)),[1,2,3]);
 await p.getByRole('button',{name:'この項目を削除',exact:true}).click();assert.deepEqual(await p.evaluate(async()=>FieldEditor.getSignatureFields().map(f=>f.signOrder)),[1,2]);assert.equal(await p.evaluate(async()=>FieldEditor.getPages()[1].fields.find(f=>f.id==='ad').linkedFieldId),'s2');
}));
test('署名欄で試し書きし、実際のPDFを確認しても契約や書式に筆跡を保存しない',async()=>withPage(async p=>{
 await seed(p,false);await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('.field-box[data-field-id=one]').click();assert.equal(await p.locator('.field-signature-preview').count(),1);
 await p.getByRole('button',{name:'この欄で試し書き',exact:true}).click();const canvas=await p.locator('#signature-test-canvas').boundingBox();await p.mouse.move(canvas.x+30,canvas.y+40);await p.mouse.down();await p.mouse.move(canvas.x+220,canvas.y+90,{steps:15});await p.mouse.up();assert.equal(await p.getByRole('button',{name:'書面で確認',exact:true}).isEnabled(),true);await p.getByRole('button',{name:'書面で確認',exact:true}).click();await p.getByRole('heading',{name:'試し印字（見本）'}).waitFor();await p.locator('.modal-backdrop canvas').first().waitFor();if(process.env.USABILITY_SCREENSHOTS)await p.screenshot({path:path.join(process.env.USABILITY_SCREENSHOTS,'signature-test-pdf.png'),fullPage:true});assert.equal(await p.evaluate(async()=>SigningFlow.getSession()),null);
 const actual=await p.evaluate(async()=>FieldEditor.getSignaturePreview('one'));assert.match(actual,/^data:image\/png;base64,/);assert.equal(await p.locator('.field-signature-preview').getAttribute('src'),actual);
 await p.getByRole('button',{name:'閉じる',exact:true}).click();await p.getByLabel('署名の表示サイズを調整').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await p.locator('.field-signature-preview').evaluate(el=>el.style.transform),'scale(0.8)');await p.getByRole('button',{name:'テンプレートを保存',exact:true}).click();await p.getByRole('button',{name:'これで署名する'}).waitFor();assert.equal(await p.evaluate(async()=>JSON.stringify(TemplateStore.exportAll()).includes('data:image/png;base64,')),false);
 await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();assert.equal(await p.evaluate(async()=>FieldEditor.getSignaturePreview('one')),undefined);
}));
test('チェック欄の印字を選び、編集見本とPDFでチェックのみ・確認済み・未確認を区別する',async()=>withPage(async p=>{
 await seed(p,false);await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);t.pages[0].fields.push(Models.createField({id:'ck',type:'declaration_checkbox',linkedFieldId:'one',x:50,y:500,width:200,height:30,label:'説明を確認'}));await TemplateStore.saveEdit(t);});await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('.field-box[data-field-id=ck]').click();await p.getByLabel('PDFに印字する内容').selectOption('check');assert.equal(await p.locator('.field-box[data-field-id=ck] .field-box-print-preview').innerText(),'✓');
 const texts=await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id),f=t.pages[0].fields.find(f=>f.id==='ck');const c=document.createElement('canvas');c.width=200;c.height=80;const ctx=c.getContext('2d');ctx.fillRect(10,20,140,3);const session=Models.createSigningSession({recipientName:'テスト',status:'completed',completedAt:new Date().toISOString()});const signer=Models.createSigner({fieldId:'one',role:'recipient',typedName:'テスト',signedAt:session.completedAt,confirmedDeclarationIds:['ck'],signatureImageDataUrl:c.toDataURL()});session.signers=[signer];const texts=[];for(const choice of ['check','confirmed','unchecked']){f.checkPrintStyle=choice==='unchecked'?'check':choice;signer.confirmedDeclarationIds=choice==='unchecked'?[]:['ck'];const bytes=await PdfWriter.buildSignedPdf(t,session);const pdf=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise;const content=await(await pdf.getPage(1)).getTextContent();texts.push(content.items.map(i=>i.str).join(''));await pdf.destroy();}return texts;});assert.match(texts[0],/✓/);assert.ok(!texts[0].includes('確認済み'));assert.match(texts[1],/✓ 確認済み/);assert.ok(!texts[2].includes('✓'));
}));

test('2つの署名セットと1人目に紐付けた4つの確認チェックを保存できる',async()=>withPage(async p=>{
 await seed(p);await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);for(const [id,signature,y] of [['n1','one',550],['n2','two',270]])t.pages[0].fields.push(Models.createField({id,type:'name',linkedFieldId:signature,x:50,y,width:200,height:30}));t.pages[0].fields.push(Models.createField({id:'a1',type:'address',linkedFieldId:'one',x:50,y:500,width:300,height:35}),Models.createField({id:'r2',type:'relationship',linkedFieldId:'two',x:50,y:220,width:180,height:30}));for(let i=0;i<4;i++)t.pages[0].fields.push(Models.createField({id:'check'+i,type:'declaration_checkbox',linkedFieldId:'one',x:400,y:500-i*50,width:120,height:30,label:'同意事項'+(i+1)}));await TemplateStore.saveEdit(t);});await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();const errors=await p.evaluate(async()=>Models.validateTemplate({pages:FieldEditor.getPages(),signingMode:'all'}));assert.deepEqual(errors,[]);
 await p.getByRole('button',{name:'試し印字を確認',exact:true}).click();await p.getByRole('heading',{name:'試し印字（見本）'}).waitFor();const downloaded=p.waitForEvent('download');await p.getByRole('button',{name:'見本PDFを保存',exact:true}).click();const pdfBytes=await fs.readFile(await(await downloaded).path());const text=await p.evaluate(async bytes=>{const doc=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise;const content=await(await doc.getPage(1)).getTextContent();await doc.destroy();return content.items.map(item=>item.str).join('');},Array.from(pdfBytes));assert.match(text,/山田 花子/);assert.equal((text.match(/✓ 確認済み/g)||[]).length,4);await p.getByRole('button',{name:'閉じる',exact:true}).click();
 await p.getByRole('button',{name:'テンプレートを保存',exact:true}).click();await p.getByRole('button',{name:'これで署名する'}).waitFor();const settings=await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);return {count:t.pages[0].fields.filter(f=>f.type==='signature').length,checks:t.pages[0].fields.filter(f=>f.type==='declaration_checkbox').map(f=>f.linkedFieldId)}});assert.equal(settings.count,2);assert.deepEqual(settings.checks,['one','one','one','one']);
}));

test('1人用の設定に2つの署名欄がある場合、保存時に意味を説明して署名方法を選べる',async()=>withPage(async p=>{
 await seed(p);await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('#template-signing-mode').selectOption('single');assert.match(await p.locator('#template-field-summary').innerText(),/署名欄：2つ/);await p.getByRole('button',{name:'試し印字を確認',exact:true}).click();await p.getByRole('heading',{name:'試し印字（見本）'}).waitFor();await p.getByRole('button',{name:'閉じる',exact:true}).click();assert.equal(await p.locator('#template-signing-mode').inputValue(),'single');await p.getByRole('button',{name:'テンプレートを保存',exact:true}).click();await p.getByRole('heading',{name:'署名欄が2つあります。署名方法を選んでください'}).waitFor();if(process.env.USABILITY_SCREENSHOTS)await p.screenshot({path:path.join(process.env.USABILITY_SCREENSHOTS,'save-signing-method.png'),fullPage:true});assert.equal(await p.evaluate(async()=>TemplateStore.get(TemplateStore.list()[0].id).signingMode),'all');await p.getByRole('button',{name:'必要な場合だけ追加の人も署名して保存',exact:true}).click();await p.getByRole('button',{name:'これで署名する'}).waitFor();assert.equal(await p.evaluate(async()=>TemplateStore.get(TemplateStore.list()[0].id).signingMode),'optional');
 await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('#template-signing-mode').selectOption('single');await p.getByRole('button',{name:'テンプレートを保存',exact:true}).click();await p.getByRole('button',{name:'全員の署名を必須にして保存',exact:true}).click();await p.getByRole('button',{name:'これで署名する'}).waitFor();assert.equal(await p.evaluate(async()=>TemplateStore.get(TemplateStore.list()[0].id).signingMode),'all');
}));
test('直前の署名欄へ氏名・住所・続柄・日付・確認チェックを自動割当し、手動変更や共通情報を区別する',async()=>withPage(async p=>{
 await p.setViewportSize({width:1360,height:1000});await seed(p,false);await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();
 async function place(label,y){await p.getByRole('button',{name:label}).click();await p.locator('#field-overlay').scrollIntoViewIfNeeded();const r=await p.locator('#field-overlay').boundingBox();await p.mouse.move(r.x+650,r.y+y);await p.mouse.down();await p.mouse.move(r.x+745,r.y+y+35,{steps:8});await p.mouse.up();return await p.evaluate(async()=>FieldEditor.getPages()[0].fields.at(-1));}
 const second=await place(/^手書き署名/,100);assert.equal(second.type,'signature');assert.equal(second.signOrder,2);assert.match(await p.locator('#field-assignment-target').innerText(),/署名欄 2/);
 for(const [label,type,y] of [[/^署名者住所欄/,'address',180],[/^署名者氏名（活字）/,'name',260],[/^続柄欄/,'relationship',340],[/^日付欄/,'date',420],[/^確認チェック欄/,'declaration_checkbox',500]]){const f=await place(label,y);assert.equal(f.type,type);assert.equal(f.linkedFieldId,second.id);}
 await p.getByLabel('どの署名欄の項目か').selectOption('one');assert.match(await p.locator('#field-assignment-target').innerText(),/署名欄 1/);const next=await place(/^署名者住所欄/,580);assert.equal(next.linkedFieldId,'one');
 const common=await place(/^利用者氏名（活字）/,660);assert.equal(common.linkedFieldId,null);assert.equal(await p.evaluate(async()=>FieldEditor.getActiveSignatureField().id),'one');
 await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);t.pages=JSON.parse(JSON.stringify(FieldEditor.getPages()));t.signingMode='all';await TemplateStore.saveEdit(t);});await p.locator('#btn-nav-home').click();await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.waitForFunction(()=>document.getElementById('field-assignment-target').textContent.includes('割り当てたい'));assert.equal(await p.evaluate(async()=>FieldEditor.getActiveSignatureField()),null);assert.match(await p.locator('#field-assignment-target').innerText(),/割り当てたい署名欄を押して/);
 await p.locator('.field-box[data-field-id="'+second.id+'"]').click();assert.equal(await p.evaluate(async()=>FieldEditor.getActiveSignatureField().signOrder),2);await p.getByRole('button',{name:'この項目を削除',exact:true}).click();assert.equal(await p.evaluate(async()=>FieldEditor.getActiveSignatureField().id),'one');
}));

test('住所見本で改行を保ち、試し印字でも住所と建物名を別行に配置する',async()=>withPage(async p=>{
 await seed(p,false);await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();const preview=p.locator('.field-box[data-field-id=ra] .field-box-print-preview');assert.match(await preview.textContent(),/\n/);assert.equal(await preview.evaluate(el=>getComputedStyle(el).whiteSpace),'pre-wrap');
 await p.locator('#preview-recipient-address').evaluate(el=>el.closest('details').open=true);await p.locator('#preview-recipient-address').fill('本人住所');await p.locator('#preview-recipient-building').fill('本人建物101');await p.getByRole('button',{name:'試し印字を確認',exact:true}).click();await p.getByRole('heading',{name:'試し印字（見本）'}).waitFor();const downloading=p.waitForEvent('download');await p.getByRole('button',{name:'見本PDFを保存',exact:true}).click();const bytes=await fs.readFile(await(await downloading).path());const lines=await p.evaluate(async bytes=>{const doc=await pdfjsLib.getDocument({data:new Uint8Array(bytes)}).promise;const content=await(await doc.getPage(1)).getTextContent();await doc.destroy();return content.items.filter(i=>['本人住所','本人建物101'].includes(i.str)).map(i=>({text:i.str,y:i.transform[5]}));},Array.from(bytes));assert.equal(lines.length,2);assert.equal(lines[0].text,'本人住所');assert.ok(lines[0].y>lines[1].y);
}));
test('住所欄の2・3・4行設定で高さを調整し、文字サイズへ追従して手動リサイズは自由調整に戻る',async()=>withPage(async p=>{
 await p.setViewportSize({width:1360,height:1000});await seed(p,false);await p.getByRole('button',{name:'署名欄を編集',exact:true}).click();await p.locator('.field-box[data-field-id=ra]').click();const getField=()=>p.evaluate(async()=>({...FieldEditor.getPages()[0].fields.find(f=>f.id==='ra')}));const original=await getField();assert.equal(original.height,50);
 await p.getByLabel('住所欄の行数（枠の高さ）').selectOption('3');const three=await getField();assert.equal(three.addressRows,3);assert.equal(three.height,67);assert.equal(three.y+three.height,original.y+original.height);
 await p.getByLabel('文字サイズを調整').evaluate(el=>{el.value='18';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal((await getField()).height,85);
 await p.getByLabel('住所欄の行数（枠の高さ）').selectOption('2');assert.equal((await getField()).height,58);
 await p.getByLabel('住所欄の行数（枠の高さ）').selectOption('4');assert.equal((await getField()).height,112);
 const corner=p.locator('.field-box[data-field-id=ra] .field-resize-se');await corner.scrollIntoViewIfNeeded();const r=await corner.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+r.width/2+15,r.y+r.height/2+15,{steps:5});await p.mouse.up();assert.equal((await getField()).addressRows,undefined);assert.equal(await p.getByLabel('住所欄の行数（枠の高さ）').inputValue(),'custom');
 await p.evaluate(async()=>{const f=FieldEditor.getPages()[0].fields.find(f=>f.id==='ra');f.y=0;f.height=20;f.addressRows=4;FieldEditor.fitAddressRows(f);FieldEditor.renderFieldBoxes();});const edge=await getField();assert.equal(edge.y,0);assert.ok(edge.y+edge.height<=842);
}));
test('本人住所の印字溢れを署名前に止め、修正後に開始できる',async()=>withPage(async p=>{
 await seed(p,false);await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);t.pages[0].fields.find(f=>f.id==='ra').width=35;t.pages[0].fields.find(f=>f.id==='ra').height=15;await TemplateStore.saveEdit(t);});
 await p.getByRole('button',{name:'これで署名する'}).click();await p.locator('#signing-recipient-name').fill('本人');await p.locator('#signing-recipient-address').fill('東京都千代田区丸の内一丁目2番3号');await p.locator('#signing-recipient-building').fill('とても長いマンション名称A棟101号室');
 const messages=[];p.on('dialog',d=>messages.push(d.message()));await p.getByRole('button',{name:'次へ進む'}).click();await p.waitForFunction(()=>!document.querySelector('#signing-stage button.big-button').disabled);
 assert.equal(await p.evaluate(()=>SigningFlow.getSession()),null);assert.ok(messages.some(m=>m.includes('枠に収まりません')));assert.equal(await p.locator('#signing-recipient-building').inputValue(),'とても長いマンション名称A棟101号室');
 await p.locator('#signing-recipient-address').fill('住所');await p.locator('#signing-recipient-building').fill('');await p.getByRole('button',{name:'次へ進む'}).click();await p.getByRole('button',{name:'続ける',exact:true}).waitFor();assert.equal(await p.evaluate(()=>SigningFlow.getSession().recipientAddress),'住所');
}));
test('署名者の住所溢れでは筆記を止め、代筆者名が本人名と同じなら確認する',async()=>withPage(async p=>{
 await seed(p,false);await p.evaluate(async()=>{const t=TemplateStore.get(TemplateStore.list()[0].id);t.pages[0].fields.push(Models.createField({id:'sa',type:'address',linkedFieldId:'one',x:50,y:500,width:35,height:15}));await TemplateStore.saveEdit(t);});
 await p.getByRole('button',{name:'これで署名する'}).click();await p.locator('#signing-recipient-name').fill('本人');await p.locator('#signing-recipient-address').fill('本人住所');await p.locator('#signing-primary-role').selectOption('family');await p.getByRole('button',{name:'次へ進む'}).click();await p.getByRole('button',{name:'続ける',exact:true}).click();await p.locator('.signing-field-highlight').click();
 const name=p.getByLabel('実際に記入するご家族のお名前',{exact:true});await name.fill('本人');assert.match(await p.locator('#scribe-name-hint').innerText(),/入力欄.*ご家族.*手書き欄.*本人/);assert.match(await name.getAttribute('placeholder'),/ご家族/);
 await p.getByLabel('記入者住所（PDF印字用・必須）',{exact:true}).fill('東京都千代田区丸の内一丁目2番3号とても長い住所');await p.getByRole('checkbox',{name:/本人が契約内容/}).check();assert.match(await p.locator('#signer-missing-reasons').innerText(),/枠に収まりません/);
 const box=await p.locator('#signature-canvas').boundingBox();async function draw(){await p.mouse.move(box.x+20,box.y+20);await p.mouse.down();await p.mouse.move(box.x+120,box.y+30,{steps:12});await p.mouse.up();}
 await draw();assert.equal(await p.getByRole('button',{name:'1画戻す',exact:true}).isEnabled(),false);
 await p.getByLabel('記入者住所（PDF印字用・必須）',{exact:true}).fill('住所');await p.evaluate(()=>{window.measureCalls=0;const original=PdfWriter.assertTextFieldsFit;PdfWriter.assertTextFieldsFit=(items)=>{window.measureCalls++;return original(items);};});await draw();assert.equal(await p.evaluate(()=>window.measureCalls),0,'筆記中に文字を再計測しない');assert.equal(await p.getByRole('button',{name:'この内容で確定する',exact:true}).isEnabled(),true);
 await p.getByRole('button',{name:'この内容で確定する',exact:true}).click();assert.equal(await p.locator('#signature-canvas').isVisible(),true);assert.equal(await p.evaluate(()=>SigningFlow.getSession().signers.length),0);
 // 同姓同名を確認して進むことも可能。筆跡は取消時に保持される。
 p.removeAllListeners('dialog');p.on('dialog',d=>d.accept());await p.getByRole('button',{name:'この内容で確定する',exact:true}).click();await p.getByRole('button',{name:'完成書面を確認',exact:true}).waitFor();assert.equal(await p.evaluate(()=>SigningFlow.getSession().signers[0].typedName),'本人');
}));
